import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { computeCommitment, computeLeaf, hashPair, verifyProof, REG_TAG, LEAF_TAG } from "./poseidon.ts";

/**
 * Phase 2's hard gate: this file's Poseidon implementation must reproduce, bit for bit, the
 * values contracts/tests/test_vectors.cairo computed with the real Cairo
 * `core::poseidon::poseidon_hash_span`. epochs/vectors.json is generated by `make
 * contracts-test` — regenerate it there if the Cairo side changes, never hand-edit it.
 */

const vectorsPath = path.join(import.meta.dirname, "..", "..", "epochs", "vectors.json");
const vectors: Record<string, string> = JSON.parse(readFileSync(vectorsPath, "utf8"));
const big = (key: string): bigint => BigInt(vectors[key]!);

test("REG_TAG / LEAF_TAG short-string encoding matches Cairo", () => {
  assert.equal(REG_TAG, big("reg_tag"));
  assert.equal(LEAF_TAG, big("leaf_tag"));
});

test("commitment/leaf vectors match Cairo for all 4 test entries", () => {
  const token = big("token");
  for (let i = 0; i < 4; i++) {
    const secret = big(`secret_${i}`);
    const total = big(`total_${i}`);
    const commitment = computeCommitment(secret);
    assert.equal(commitment, big(`commitment_${i}`), `commitment_${i} mismatch`);
    const leaf = computeLeaf(commitment, token, total);
    assert.equal(leaf, big(`leaf_${i}`), `leaf_${i} mismatch`);
  }
});

test("4-leaf sorted-pair merkle root matches Cairo", () => {
  const leaves = [0, 1, 2, 3].map((i) => big(`leaf_${i}`));
  const node0 = hashPair(leaves[0]!, leaves[1]!);
  const node1 = hashPair(leaves[2]!, leaves[3]!);
  const root = hashPair(node0, node1);
  assert.equal(root, big("root"));
});

test("verifyProof accepts a correct proof and rejects a wrong one", () => {
  const leaves = [0, 1, 2, 3].map((i) => big(`leaf_${i}`));
  const node1 = hashPair(leaves[2]!, leaves[3]!);
  const root = big("root");

  assert.ok(verifyProof(leaves[0]!, [leaves[1]!, node1], root));
  assert.ok(!verifyProof(leaves[0]!, [leaves[2]!, node1], root));
});
